runtime: python
env: flex
entrypoint: gunicorn -b :$PORT wsgi:app

runtime_config:
  python_version: 3

env_variables:
  FLASK_CONFIG: unix
  DATABASE_URI: mysql+pymysql://username:password@/blog_db?unix_socket=/cloudsql/elated-lotus-155121:us-east1:blog
  BLOG_ADMIN: rmharriman@gmail.com
  MAIL_USERNAME: rmharriman@gmail.com
  SECRET_KEY: dkajfeourwoeuhsdjhjvzcxbzmvbshfiuehihjdhjfshajdfhieryuhg3849642ilsdjfkshof2328fhwi
  SSL_DISABLE: 1

beta_settings:
      cloud_sql_instances: elated-lotus-155121:us-east1:blog
